apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portfolio
  name: portfolio
  namespace: "dev"
spec:
  replicas: 2
  selector:
    app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      minReadySeconds: 0
      revisionHistoryLimit: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
      containers:
      - image: cinnojam/cinnojam:portfolio
        name: portfolio
        ports:
        - containerPort: 8080
          name: backend-http
