apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio
  namespace: "development"
spec:
  ports:
  - port: 8080
    name: http
    targetPort: backend-http
  selector: 
    app: portfolio
  type: LoadBalancer
