apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portfolio
  name: portfolio
  namespace: "production"
spec:
  replicas: 2
  selector:
#    app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
#      minReadySeconds: 0
#      revisionHistoryLimit: 1
#      strategy:
#       type: RollingUpdate
#        rollingUpdate:
#          maxSurge: 1
#          maxUnavailable: 1
      imagePullPolicy: Always
      containers:
      - image: cinnojam/portfolio:dev
        name: portfolio
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: backend-http
