apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: exercise
  name: exercise
spec:
  replicas: 2
  selector:
    app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
      - image: cinnojam/cinnojam:exercise
        name: exercise
        ports:
        - containerPort: 8080
          name: backend-http
