spring:
  datasource: 
    continue-on-error: true
    url: jdbc:mysql://localhost:3306/portfolio
    username: user
    password: pwd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /${spring.application.name}
